//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_BD.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leads__Ponturi_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Leads__Ponturi_()
        {
            this.Evenimentes = new HashSet<Evenimente>();
            this.Potential_client_ = new HashSet<Potential_client_>();
        }
    
        public int Lead_ID { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public Nullable<decimal> Nr_tel { get; set; }
        public string Email { get; set; }
        public string Companie { get; set; }
        public Nullable<System.DateTime> Contact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evenimente> Evenimentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Potential_client_> Potential_client_ { get; set; }
    }
}
