//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_BD.Resources
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model_CRM : DbContext
    {
        public Model_CRM()
            : base("name=Model_CRM")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Leads__Ponturi_> Leads__Ponturi_ { get; set; }
        public virtual DbSet<Utilizatori> Utilizatoris { get; set; }
        public virtual DbSet<Evenimente> Evenimentes { get; set; }
        public virtual DbSet<Potential_client_> Potential_client_ { get; set; }
    }
}
